version: '3'

volumes:
  postgres_data: {}

services:
  app:
    image: node:alpine
    container_name: encurtador_app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../..:/www
    command: /bin/sh -c "if [ $NODE_ENV==='development' ];then npm run start:dev;fi; npm run start"
    working_dir: /www
    env_file: ../../.dev/.env
    environment:
      - DB_HOST=db
    external_links:
      - db
  db:
    image: postgres:13
    container_name: encurtador_db
    env_file: ../../.dev/.env
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
